// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockPasswordHasher is an autogenerated mock type for the PasswordHasher type
type MockPasswordHasher struct {
	mock.Mock
}

type MockPasswordHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordHasher) EXPECT() *MockPasswordHasher_Expecter {
	return &MockPasswordHasher_Expecter{mock: &_m.Mock}
}

// ComparePasswordAndHash provides a mock function with given fields: password, hash
func (_m *MockPasswordHasher) ComparePasswordAndHash(password string, hash string) (bool, error) {
	ret := _m.Called(password, hash)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return rf(password, hash)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(password, hash)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(password, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPasswordHasher_ComparePasswordAndHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComparePasswordAndHash'
type MockPasswordHasher_ComparePasswordAndHash_Call struct {
	*mock.Call
}

// ComparePasswordAndHash is a helper method to define mock.On call
//   - password string
//   - hash string
func (_e *MockPasswordHasher_Expecter) ComparePasswordAndHash(password interface{}, hash interface{}) *MockPasswordHasher_ComparePasswordAndHash_Call {
	return &MockPasswordHasher_ComparePasswordAndHash_Call{Call: _e.mock.On("ComparePasswordAndHash", password, hash)}
}

func (_c *MockPasswordHasher_ComparePasswordAndHash_Call) Run(run func(password string, hash string)) *MockPasswordHasher_ComparePasswordAndHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockPasswordHasher_ComparePasswordAndHash_Call) Return(_a0 bool, _a1 error) *MockPasswordHasher_ComparePasswordAndHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPasswordHasher_ComparePasswordAndHash_Call) RunAndReturn(run func(string, string) (bool, error)) *MockPasswordHasher_ComparePasswordAndHash_Call {
	_c.Call.Return(run)
	return _c
}

// HashPassword provides a mock function with given fields: password
func (_m *MockPasswordHasher) HashPassword(password string) (string, error) {
	ret := _m.Called(password)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPasswordHasher_HashPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashPassword'
type MockPasswordHasher_HashPassword_Call struct {
	*mock.Call
}

// HashPassword is a helper method to define mock.On call
//   - password string
func (_e *MockPasswordHasher_Expecter) HashPassword(password interface{}) *MockPasswordHasher_HashPassword_Call {
	return &MockPasswordHasher_HashPassword_Call{Call: _e.mock.On("HashPassword", password)}
}

func (_c *MockPasswordHasher_HashPassword_Call) Run(run func(password string)) *MockPasswordHasher_HashPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPasswordHasher_HashPassword_Call) Return(_a0 string, _a1 error) *MockPasswordHasher_HashPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPasswordHasher_HashPassword_Call) RunAndReturn(run func(string) (string, error)) *MockPasswordHasher_HashPassword_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockPasswordHasher interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockPasswordHasher creates a new instance of MockPasswordHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockPasswordHasher(t mockConstructorTestingTNewMockPasswordHasher) *MockPasswordHasher {
	mock := &MockPasswordHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
