// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "game/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockLeaderboardService is an autogenerated mock type for the LeaderboardService type
type MockLeaderboardService struct {
	mock.Mock
}

type MockLeaderboardService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLeaderboardService) EXPECT() *MockLeaderboardService_Expecter {
	return &MockLeaderboardService_Expecter{mock: &_m.Mock}
}

// GetLeaderboard provides a mock function with given fields: ctx
func (_m *MockLeaderboardService) GetLeaderboard(ctx context.Context) (domain.Leaderboard, error) {
	ret := _m.Called(ctx)

	var r0 domain.Leaderboard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (domain.Leaderboard, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) domain.Leaderboard); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(domain.Leaderboard)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLeaderboardService_GetLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeaderboard'
type MockLeaderboardService_GetLeaderboard_Call struct {
	*mock.Call
}

// GetLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLeaderboardService_Expecter) GetLeaderboard(ctx interface{}) *MockLeaderboardService_GetLeaderboard_Call {
	return &MockLeaderboardService_GetLeaderboard_Call{Call: _e.mock.On("GetLeaderboard", ctx)}
}

func (_c *MockLeaderboardService_GetLeaderboard_Call) Run(run func(ctx context.Context)) *MockLeaderboardService_GetLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLeaderboardService_GetLeaderboard_Call) Return(_a0 domain.Leaderboard, _a1 error) *MockLeaderboardService_GetLeaderboard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLeaderboardService_GetLeaderboard_Call) RunAndReturn(run func(context.Context) (domain.Leaderboard, error)) *MockLeaderboardService_GetLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitUserScore provides a mock function with given fields: ctx, userID, score
func (_m *MockLeaderboardService) SubmitUserScore(ctx context.Context, userID string, score float64) error {
	ret := _m.Called(ctx, userID, score)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64) error); ok {
		r0 = rf(ctx, userID, score)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLeaderboardService_SubmitUserScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitUserScore'
type MockLeaderboardService_SubmitUserScore_Call struct {
	*mock.Call
}

// SubmitUserScore is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - score float64
func (_e *MockLeaderboardService_Expecter) SubmitUserScore(ctx interface{}, userID interface{}, score interface{}) *MockLeaderboardService_SubmitUserScore_Call {
	return &MockLeaderboardService_SubmitUserScore_Call{Call: _e.mock.On("SubmitUserScore", ctx, userID, score)}
}

func (_c *MockLeaderboardService_SubmitUserScore_Call) Run(run func(ctx context.Context, userID string, score float64)) *MockLeaderboardService_SubmitUserScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(float64))
	})
	return _c
}

func (_c *MockLeaderboardService_SubmitUserScore_Call) Return(_a0 error) *MockLeaderboardService_SubmitUserScore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLeaderboardService_SubmitUserScore_Call) RunAndReturn(run func(context.Context, string, float64) error) *MockLeaderboardService_SubmitUserScore_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockLeaderboardService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockLeaderboardService creates a new instance of MockLeaderboardService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockLeaderboardService(t mockConstructorTestingTNewMockLeaderboardService) *MockLeaderboardService {
	mock := &MockLeaderboardService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
